function generateApiFetch(options?: { baseURL?: string }): string {
  const baseURL = options?.baseURL
  const lines: string[] = []
  lines.push('/* eslint-disable */')
  lines.push('/* This file is auto-generated by apigen. Do not edit. */')
  lines.push('')
  lines.push('export function apiFetch<T>(path: string, init?: RequestInit): Promise<T> {')
  if (baseURL) {
    lines.push(`  return fetch(\`${baseURL}\${path}\`, {`)
  } else {
    lines.push('  return fetch(path, {')
  }
  lines.push("    headers: { 'Content-Type': 'application/json' },")
  lines.push('    ...init,')
  lines.push('  }).then(res => {')
  lines.push('    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`)')
  lines.push('    return res.json() as Promise<T>')
  lines.push('  })')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

export { generateApiFetch }
