function generateIndexFile(options?: { mock?: boolean; includeProvider?: boolean }): string {
  const mock = options?.mock ?? true
  const includeProvider = options?.includeProvider ?? true
  const lines = [
    '/* eslint-disable */',
    '/* This file is auto-generated by apigen. Do not edit. */',
    '',
    "export * from './types'",
    "export * from './hooks'",
  ]
  if (mock) {
    lines.push("export * from './mocks'")
    if (includeProvider) {
      lines.push("export * from './test-mode-provider'")
    }
  }
  lines.push('')
  return lines.join('\n')
}

function generateRootIndexFile(tagSlugs: string[], options?: { mock?: boolean }): string {
  const mock = options?.mock ?? true
  const lines = [
    '/* eslint-disable */',
    '/* This file is auto-generated by apigen. Do not edit. */',
    '',
  ]
  for (const slug of tagSlugs) {
    lines.push(`export * from './${slug}'`)
  }
  if (mock) {
    lines.push("export * from './test-mode-provider'")
  }
  lines.push('')
  return lines.join('\n')
}

export { generateIndexFile, generateRootIndexFile }
