function generateIndexFile(): string {
  return `/* eslint-disable */
/* This file is auto-generated by apigen. Do not edit. */

export * from './types'
export * from './hooks'
export * from './mocks'
export * from './test-mode-provider'
`
}

export { generateIndexFile }
