function generateProvider(): string {
  return `/* eslint-disable */
/* This file is auto-generated by apigen. Do not edit. */

import { createContext, useContext, type ReactNode } from 'react'

interface ApiTestModeContext {
  enabled: boolean
}

const ApiTestModeCtx = createContext<ApiTestModeContext>({ enabled: false })

export function ApiTestModeProvider({
  enabled,
  children,
}: {
  enabled: boolean
  children: ReactNode
}) {
  return (
    <ApiTestModeCtx.Provider value={{ enabled }}>
      {children}
    </ApiTestModeCtx.Provider>
  )
}

export function useApiTestMode(): ApiTestModeContext {
  return useContext(ApiTestModeCtx)
}
`
}

export { generateProvider }
