import type { IR, IRSchema, IROperation, IRProperty } from '../ir'

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function tsType(prop: IRProperty): string {
  if (prop.isArray) {
    const inner = prop.itemType ?? 'unknown'
    return `${inner}[]`
  }
  if (prop.ref) {
    const refName = prop.ref.split('/').pop() ?? 'unknown'
    return refName
  }
  return prop.type
}

function generateSchemaInterface(schema: IRSchema): string {
  const lines: string[] = []
  lines.push(`export interface ${schema.name} {`)
  for (const prop of schema.properties) {
    const optional = prop.required ? '' : '?'
    lines.push(`  ${prop.name}${optional}: ${tsType(prop)}`)
  }
  lines.push('}')
  return lines.join('\n')
}

function generateParamsInterface(op: IROperation): string | null {
  const allParams = [...op.pathParams, ...op.queryParams]
  if (allParams.length === 0) return null

  const name = `${capitalize(op.operationId)}Params`
  const lines: string[] = []
  lines.push(`export interface ${name} {`)
  for (const param of allParams) {
    const optional = param.required ? '' : '?'
    lines.push(`  ${param.name}${optional}: ${param.type}`)
  }
  lines.push('}')
  return lines.join('\n')
}

function generateTypes(ir: IR): string {
  const parts: string[] = []

  parts.push('/* eslint-disable */')
  parts.push('/* This file is auto-generated by apigen. Do not edit. */')
  parts.push('')

  for (const schema of ir.schemas) {
    parts.push(generateSchemaInterface(schema))
    parts.push('')
  }

  for (const op of ir.operations) {
    const paramsInterface = generateParamsInterface(op)
    if (paramsInterface) {
      parts.push(paramsInterface)
      parts.push('')
    }
  }

  return parts.join('\n')
}

export { generateTypes }
